name: "Chore / Task"
description: Housekeeping, refactors, CI, docs—no user-visible change.
title: "chore(scope): short description"
labels: ["type:chore", "priority:P2"]
body:
  - type: textarea
    id: task
    attributes:
      label: Task
      description: What will be done?
    validations:
      required: true
  - type: textarea
    id: done
    attributes:
      label: Definition of Done
      placeholder: |
        - CI green
        - README adjusted (if needed)
        - No behavior changes
