name: Add issues to project

on:
  issues:
    types: [opened]

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - name: Add to project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/thenarfer/projects/1
          github-token: ${{ secrets.PROJECT_TOKEN }} # PAT with repo + project scopes