name: Add issues to project

on:
  issues:
    types: [opened]

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/users/thenarfer/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # If you have a “Status” field in the project:
          fields: |
            Status=Backlog
