name: ci
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps if present
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f app/requirements.txt ]; then pip install -r app/requirements.txt; fi
      - name: Quick syntax checks
        run: |
          if [ -f app/main.py ]; then python -m py_compile app/main.py; fi
          if [ -f ./spin ]; then chmod +x ./spin; ./spin --help; fi
