name: ci
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install (editable) + test deps
        run: |
          python -m pip install -U pip
          pip install -e .[test]
      - name: CLI smoke
        run: spin --help
      - name: Run tests
        run: pytest -q
