name: pr-requires-issue

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: read
  statuses: write

jobs:
  check:
    name: PR references issue
    runs-on: ubuntu-latest
    steps:
      - name: Enforce "Closes #<id>"
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const body = pr.body || '';
            const title = pr.title || '';
            const labels = (pr.labels || []).map(l => l.name);
            // allow explicit bypass
            if (labels.includes('no-issue')) {
              core.notice("Bypassed via 'no-issue' label.");
              return;
            }
            const re = /(close[sd]?|fix(e[sd])?|resolve[sd]?)\s+#\d+/i;
            if (!re.test(body) && !re.test(title)) {
              core.setFailed("PR must reference an Issue (e.g. 'Closes #22'). Add the 'no-issue' label to bypass with justification.");
            }
