name: pr-tests-required

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

permissions:
  contents: read
  pull-requests: read
  statuses: write

jobs:
  gate:
    name: Tests changed when src changes
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - 'src/**'
            tests:
              - 'tests/**'

      - name: Enforce tests presence
        uses: actions/github-script@v7
        env:
          HAS_SRC: ${{ steps.filter.outputs.src }}
          HAS_TESTS: ${{ steps.filter.outputs.tests }}
        with:
          script: |
            const hasSrc = process.env.HAS_SRC === 'true';
            const hasTests = process.env.HAS_TESTS === 'true';
            const labels = context.payload.pull_request.labels?.map(l => l.name) || [];
            const bypass = labels.includes('skip-tests');
            if (hasSrc && !hasTests && !bypass) {
              core.setFailed("Files under 'src/' changed but no tests under 'tests/'. Add tests or apply the 'skip-tests' label with justification.");
            } else if (hasSrc && !hasTests && bypass) {
              core.notice("Bypassed via 'skip-tests' label.");
            } else {
              core.notice("OK: tests present or src unchanged.");
            }
