name: semantic-pr

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  statuses: write
  pull-requests: read

jobs:
  lint:
    name: Semantic PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            chore
            docs
            refactor
            test
            ci
            build
          requireScope: false
          # Require a non-empty subject
          subjectPattern: ^[^\s].+
          # Permit "WIP:" prefixes while iterating
          wip: true
